//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiClientWpf.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderForDriver
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> AgeDrivers { get; set; }
        public Nullable<int> IdEmpooy { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Emplooy Emplooy { get; set; }
    }
}
