//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiDriwerWpf.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OchenkaZaOrder = new HashSet<OchenkaZaOrder>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> TaxistId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string AddressStart { get; set; }
        public string AddressEnd { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TypePaymentId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> IsAccept { get; set; }
    
        public virtual Emplooy Emplooy { get; set; }
        public virtual Emplooy Emplooy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OchenkaZaOrder> OchenkaZaOrder { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Type Type { get; set; }
    }
}
